config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "projects#index"
  resources :projects
  resources :employees
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  validates :name, presence:{message: "Enter Name"}, length: { maximum: 25 }
  validates :address, presence:{message: "Enter address"}
  validates :age, presence:{message: "Enter age"}, numericality: { only_integer: true, message: "Invalid age" }
  validates :salary, presence:{message: "Enter salary"}, numericality: { only_integer: true, message: "Invalid salary" }

  belongs_to :project
  validates :project, presence:{message: "Select project"}
end

app/models/project.rb
class Project < ApplicationRecord
  validates :name, presence:true, length: { maximum: 25 }
  has_many :employees
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def new
    @employee = Employee.new

  end

  def create
    employee = Employee.new(employee_save_params)
    if employee.save
      flash[:success] = "Employee Saved!"
      redirect_to employees_path
    else
      flash[:alert] = employee.errors.messages
      redirect_to :action => 'new'
    end
  end

  def index
    @employees = Employee.all
  end

  def destroy
    employee = Employee.find(employee_params[:id])
    employee.destroy
    flash[:notice] = "Employee Deleted"
    redirect_to employees_path
  end

  def edit
    @employee = Employee.find(employee_params[:id])
  end

  def update
    employee = Employee.find(employee_params[:id])
    if employee.update(employee_save_params)
      flash[:success] = "Employee Updated"
      redirect_to employees_path
    else
      flash[:alert] = employee.errors.messages
      redirect_to edit_employee_path
    end

  end

  private

  def employee_save_params
    params.require(:employee).permit(:name, :address, :age, :salary, :project_id)
  end

  def employee_params
    params.permit(:id)
  end

end

app/controllers/projects_controller.rb
# :nodoc:
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    project = Project.new(project_save_params)
    # project.save ? render 'index' : render 'new'
    if project.save
      flash[:success] = "Project Saved!"
      redirect_to root_path
    else
      flash[:alert] = "Invalid project name!"
      redirect_to :action => 'new'
    end
  end

    def destroy
      project = Project.find(project_params[:id])
      project.destroy
      flash[:notice] = "Project Deleted"
      redirect_to root_path
    end

  def edit
    @project = Project.find(project_params[:id])
  end

  def update
    project = Project.find(project_params[:id])
    if project.update(project_save_params)
      flash[:success] = "Project Updated"
      redirect_to root_path
    else
      flash[:alert] = "Error updating project!"
      redirect_to edit_project_path
    end

  end


  private

  def project_save_params
    params.require(:project).permit(:name, :description)
  end

  def project_params
    params.permit(:id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/employees/edit.html.erb
<style>
  span{
    float:right;
    color:red;
  }
</style>

<div style="width:50%;margin: 0 auto;">
  <%= bootstrap_form_with(model: @employee, local: true) do |f| %>

    <% if !flash[:alert].nil? && !flash[:alert].dig("name").nil? %>
      <span><%= flash[:alert]["name"][0] %></span>
    <% end %>
    <%= f.text_field :name %>

    <% if !flash[:alert].nil? && !flash[:alert].dig("address").nil? %>
      <span><%= flash[:alert]["address"][0] %></span>
    <% end %>
    <%= f.text_field :address %>

    <% if !flash[:alert].nil? && !flash[:alert].dig("age").nil? %>
      <span><%= flash[:alert]["age"][0] %></span>
    <% end %>
    <%= f.text_field :age %>

    <% if !flash[:alert].nil? && !flash[:alert].dig("salary").nil? %>
      <span><%= flash[:alert]["salary"][0] %></span>
    <% end %>
    <%= f.text_field :salary %>

    <% if !flash[:alert].nil? && !flash[:alert].dig("project").nil? %>
      <span><%= flash[:alert]["project"][1] %></span>
    <% end %>
    <%= f.select :project_id, Project.all.collect { |p| [p.name, p.id] }, include_blank: true %>

    <%= f.submit "Update" %>
  <% end %>
</div>

app/views/employees/index.html.erb
<% flash.each do |name, msg| -%>
  <% if name=='alert' %>
    <%= content_tag :div, msg, class: "alert alert-danger" %>
  <% else %>
    <%= content_tag :div, msg, class: "alert alert-success" %>
  <% end %>
<% end -%>
<% if @employees.empty? %>
  <h2 align="center">No Employees Yet</h2>
<% else %>
  <br>
  <table class="table table-dark">
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Age</th>
      <th>Salary</th>
      <th>Project</th>
    </tr>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %></td>
        <td><%= employee.address %></td>
        <td><%= employee.age %></td>
        <td><%= employee.salary %></td>
        <td><%= employee.project.name %></td>
        <td>
          <%= link_to "Edit" , edit_employee_path(employee),
                      class: "btn btn-success  " %>
          <%= link_to "Delete" ,employee_path(employee),
                      method: :delete,
                      data: { confirm: 'Are you sure?' },
                      class: "btn btn-danger  " %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/employees/new.html.erb
<style>
  span{
    float:right;
    color:red;
  }
</style>
<br>
<div style="width:50%;margin: 0 auto;">
  <%= bootstrap_form_for(@employee) do |f| %>
    <% if !flash[:alert].nil? && !flash[:alert].dig("name").nil? %>
      <span><%= flash[:alert]["name"][0] %></span>
    <% end %>
    <%= f.text_field :name %>

    <% if !flash[:alert].nil? && !flash[:alert].dig("address").nil? %>
      <span><%= flash[:alert]["address"][0] %></span>
    <% end %>
    <%= f.text_field :address %>

    <% if !flash[:alert].nil? && !flash[:alert].dig("age").nil? %>
      <span><%= flash[:alert]["age"][0] %></span>
    <% end %>
    <%= f.text_field :age %>

    <% if !flash[:alert].nil? && !flash[:alert].dig("salary").nil? %>
      <span><%= flash[:alert]["salary"][0] %></span>
    <% end %>
    <%= f.text_field :salary %>

    <% if !flash[:alert].nil? && !flash[:alert].dig("project").nil? %>
      <span><%= flash[:alert]["project"][1] %></span>
    <% end %>
    <%= f.select :project_id, Project.all.collect { |p| [p.name, p.id] }, include_blank: true %>

    <br>
    <%= f.submit "Save" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codyssey</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>


  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "Codyssey" , root_path,class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to "Home" , root_path,class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add Project" , new_project_path,class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Add Employee" , new_employee_path,class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Manage Employee" , employees_path,class: "nav-link" %>
        </li>
      </ul>
    </div>
  </nav>



    <%= yield %>
  </body>
</html>

app/views/projects/edit.html.erb
<div style="width:50%;margin: 0 auto;">
  <%= bootstrap_form_with(model: @project, local: true) do |f| %>
    <%= f.text_field :name %>
    <%= f.text_area :description %>
    <%= f.submit "Update" %>
  <% end %>
</div>

app/views/projects/index.html.erb
<% flash.each do |name, msg| -%>
  <% if name=='alert' %>
    <%= content_tag :div, msg, class: "alert alert-danger" %>
  <% else %>
    <%= content_tag :div, msg, class: "alert alert-success" %>
  <% end %>
<% end -%>
<% if @projects.empty? %>
  <h2 align="center">No Projects Yet</h2>
<% else %>
  <br>
<table class="table table-dark">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Number of Employee</th>
    <th>Action</th>
  </tr>
  <% @projects.each do |project| %>
    <tr>
      <td><%= project.name %></td>
      <td><%= project.description %></td>
      <td><%= project.employees.length %></td>
      <td>
        <%= link_to "Edit" , edit_project_path(project),
                    class: "btn btn-success  " %>
        <%= link_to "Delete" ,project_path(project),
                    method: :delete,
                    data: { confirm: 'Are you sure?' },
                    class: "btn btn-danger  " %>
      </td>
    </tr>
  <% end %>
</table>
<% end %>

app/views/projects/new.html.erb
<% flash.each do |name, msg| -%>
  <% if name=='alert' %>
    <%= content_tag :div, msg, class: "alert alert-danger" %>
  <% else %>
    <%= content_tag :div, msg, class: "alert alert-success" %>
  <% end %>
<% end -%>
<div style="width:50%;margin: 0 auto;" >
  <%= bootstrap_form_for(@project) do |f| %>
    <%= f.text_field :name %>
    <%= f.text_area :description %>
    <%= f.submit "Save" %>
  <% end %>
</div>